apiVersion: v1
kind: ConfigMap
metadata:
  name: careerpolitics-config
  namespace: production
data:
  RAILS_ENV: "production"
  NODE_ENV: "production"
  ALGOLIA_DISPLAY_BRANDING: "true"
  ALGOLIA_APPLICATION_ID: "EX5A5LT1RT"
  APP_DOMAIN: "careerpolitics.com"
  APP_PROTOCOL: "https://"
  AWS_BUCKET_NAME: "careerpolitics-image-bucket"
  AWS_S3_INPUT_BUCKET: "careerpolitics-image-bucket"
  AWS_S3_VIDEO_ID: ""
  AWS_S3_VIDEO_KEY: ""
  AWS_UPLOAD_ACL: ""
  AWS_UPLOAD_REGION: "ap-south-1"
  DO_SPACES_ENDPOINT: "https://blr1.digitaloceanspaces.com"
  DO_SPACES_CDN_ENDPOINT: ""
  BUFFER_ACCESS_TOKEN: "Optional"
  BUFFER_FACEBOOK_ID: "Optional"
  BUFFER_LINKEDIN_ID: "Optional"
  BUFFER_LISTINGS_PROFILE: "Optional"
  BUFFER_PROFILE_ID: "0"
  BUFFER_TWITTER_ID: "Optional"
  CLOUDINARY_CLOUD_NAME: "dl9zoitzq"
  CLOUDINARY_SECURE: "true"
  COMMUNITY_NAME: "Career Politics"
  COVERAGE: "false"
  DATABASE_NAME: "careerpolitics_prod"
  DATABASE_POOL_SIZE: "3"
  DEFAULT_EMAIL: "support@careerpolitics.com"
  FASTLY_SERVICE_ID: "ps1mr9jClCxL98m64HMIrF"
  FASTLY_API_KEY: ""
  FORCE_SSL_IN_RAILS: "true"
  GA_ANALYTICS_4_ID: "G-SX49NJTWXJ"
  GA_TRACKING_ID: ""
  GITHUB_KEY: "Optional"
  GITHUB_SECRET: "Optional"
  HCTI_API_KEY: "Optional"
  HCTI_API_USER_ID: "Optional"
  LANG: "en_US.UTF-8"
  OPENRESTY_URL: ""
  RACK_ENV: "production"
  RACK_TIMEOUT_SERVICE_TIMEOUT: "100000"
  RACK_TIMEOUT_WAIT_TIMEOUT: "100000"
  RAILS_LOG_TO_STDOUT: "enabled"
  RAILS_MAX_THREADS: "2"
  RAILS_SERVE_STATIC_FILES: "enabled"
  SESSION_EXPIRY_SECONDS: "1209600"
  SESSION_KEY: "_Career_Politics_Session"
  SMTP_ADDRESS: "smtp.hostinger.com"
  SMTP_AUTHENTICATION: "login"
  SMTP_DOMAIN: "careerpolitics.com"
  SMTP_PORT: "587"
  WEB_CONCURRENCY: "2"
  REDIRECT_WWW_TO_ROOT: "true"
