apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerpolitics-worker
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careerpolitics
      component: worker
  template:
    metadata:
      labels:
        app: careerpolitics
        component: worker
    spec:
      containers:
        - name: worker
          command: ["bundle", "exec", "sidekiq"]
          env:
            - name: RAILS_ENV
            - name: NODE_ENV
            - name: APP_DOMAIN
              value: "careerpolitics.in"
            - name: APP_PROTOCOL
              value: "https://"
            - name: AWS_BUCKET_NAME
              value: "careerpolitics-image-bucket"
            - name: WEB_CONCURRENCY
              value: "2"
