apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerpolitics-worker
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careerpolitics
      component: worker
  template:
    metadata:
      labels:
        app: careerpolitics
        component: worker
    spec:
      containers:
        - name: worker
          image: muraridevv/careerpolitics-platform:latest
          command: ["bundle", "exec", "sidekiq"]
          env:
            # Sensitive
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: careerpolitics-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: careerpolitics-secrets
                  key: SECRET_KEY_BASE
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: careerpolitics-secrets
                  key: AWS_SECRET
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: careerpolitics-secrets
                  key: SMTP_PASSWORD
            # Non-sensitive
            - name: RAILS_ENV
              value: production
            - name: NODE_ENV
              value: production
            - name: APP_DOMAIN
              value: "careerpolitics.in"
            - name: APP_PROTOCOL
              value: "https://"
            - name: AWS_BUCKET_NAME
              value: "careerpolitics-image-bucket"
            - name: WEB_CONCURRENCY
              value: "2"
            # Add other non-sensitive envs here
