apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerpolitics-worker
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careerpolitics
      component: worker
  template:
    metadata:
      labels:
        app: careerpolitics
        component: worker
    spec:
      containers:
        - name: worker
          image: muraridevv/careerpolitics-platform:latest
          command: ["bundle", "exec", "sidekiq"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: careerpolitics-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: careerpolitics-secrets
                  key: SECRET_KEY_BASE
            # other env vars
