apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: careerpolitics-ingress
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - careerpolitics.com
      secretName: careerpolitics-tls
  rules:
    - host: careerpolitics.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: careerpolitics-web
                port:
                  number: 3000
