apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerpolitics-sidekiq
  labels:
    app: careerpolitics
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: careerpolitics
      component: sidekiq
  template:
    metadata:
      labels:
        app: careerpolitics
        component: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
