apiVersion: v1
kind: Secret
metadata:
  name: careerpolitics-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | quote }}
  AWS_SECRET: {{ .Values.aws.secret | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  REDIS_URL: {{ .Values.redis.url | quote }}
