apiVersion: v1
kind: Service
metadata:
  name: {{ include "careerpolitics.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "careerpolitics.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: careerpolitics
    component: web
