apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forem.fullname" . }}-env
  labels:
    {{- include "forem.labels" . | nindent 4 }}

data:
  {{- range $key, $value := .Values.rails.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}