apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forem.fullname" . }}-web
  labels:
    {{- include "forem.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  revisionHistoryLimit: {{ .Values.web.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "forem.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "forem.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "forem.fullname" . }}
      {{- else if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        {{- if .Values.web.securityContext.enabled }}
        runAsNonRoot: {{ .Values.web.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.web.securityContext.runAsUser }}
        runAsGroup: {{ .Values.web.securityContext.runAsGroup }}
        fsGroup: {{ .Values.web.securityContext.fsGroup }}
        {{- end }}
      {{- with .Values.web.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.web.command }}
          command: {{- toYaml .Values.web.command | nindent 12 }}
          {{- end }}
          {{- if .Values.web.args }}
          args: {{- toYaml .Values.web.args | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            {{- with .Values.web.extraEnv }}
            {{- range . }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "forem.fullname" . }}-env
            {{- range .Values.rails.envFrom }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- range .Values.web.extraEnvFrom }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if not .Values.rails.existingSecretName }}
            - secretRef:
                name: {{ include "forem.fullname" . }}-secret
            {{- else }}
            - secretRef:
                name: {{ .Values.rails.existingSecretName }}
            {{- end }}
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: public
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            {{- with .Values.web.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      initContainers:
        {{- with .Values.web.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: public
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "forem.fullname" . }}
          {{- end }}
        {{- end }}
        {{- with .Values.web.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}