{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "forem.fullname" . }}-web
  labels:
    {{- include "forem.labels" . | nindent 4 }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "forem.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}