{{- if not .Values.rails.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forem.fullname" . }}-secret
  labels:
    {{- include "forem.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.rails.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}