apiVersion: v2              # must be v2 for Helm 3+
name: careerpolitics        # chart name
description: "CareerPolitics app Kubernetes deployment"
version: 0.1.0              # chart version
appVersion: "1.0.0"         # your app version
icon: https://example.com/logo.png
keywords:
  - career
  - politics
  - webapp
maintainers:
  - name: Murari Kumar
    email: murari@example.com
