replicaCountWeb: 2
replicaCountWorker: 1

image:
  repository: muraridevv/careerpolitics-platform
  tag: latest
  pullPolicy: IfNotPresent

namespace: production

ingress:
  host: careerpolitics.in
  tlsSecretName: careerpolitics-tls

database:
  url: "postgresql://doadmin:AVNS_Wn_xOCvNSCfyhgjMxxb@postgresql-db-do-user-24455640-0.d.db.ondigitalocean.com:25060/defaultdb?sslmode=require"

redis:
  url: "redis://careerpolitics-redis-master.redis.svc.cluster.local:6379"

aws:
  secret: "<AWS_SECRET>"
  bucketName: "careerpolitics-image-bucket"
  region: "ap-south-1"

smtp:
  password: "<SMTP_PASSWORD>"
  user: "info@careerpolitics.in"

secretKeyBase: "<SECRET_KEY_BASE>"

env:
  RAILS_ENV: production
  NODE_ENV: production
  ALGOLIA_API_KEY: "1efc4ecc26614f14e8cf68851e88014b"
  ALGOLIA_APPLICATION_ID: "EX5A5LT1RT"
  ALGOLIA_DISPLAY_BRANDING: "true"
  ALGOLIA_SEARCH_ONLY_API_KEY: "fc0ff65e9f4c6a75888b66a12ba66cf0"
  APP_DOMAIN: "careerpolitics.in"
  APP_PROTOCOL: "https://"
  # ... add all other non-sensitive env vars here
